[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
inotify = { version = "0.11.0", default-features = false }
jni = "0.21.1"
jni_fn = "0.1.2"
tar = "0.4.41"
