name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle

    - name: Setup Flutter SDK
      uses: flutter-actions/setup-flutter@v4
      with:
        channel: stable

    - name: Setup Rust
      uses: moonrepo/setup-rust@v1

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Setup Ndk
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r27
        link-to-sdk: true
    - name: Setup Ndk
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r28
        link-to-sdk: true
        
    - name: Flutter
      run: flutter -v doctor
      
    - name: Cargo
      run: cargo
      
    - name: Ls
      run: cd ./terminal_view && flutter pub get && ls .android && cd ..
    
    - name: Build with Gradle
      run: ./gradlew assembleRelease
    - name: Upload APK Debug - ${{ env.repository_name }}
      uses: actions/upload-artifact@v4
      with:
         name: Apk generated
         path: ./build/outputs/apk/debug/
